
server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: GateWay-service

  cloud:
    gateway:
      routes:
        - id : default-root
          uri: http://localhost:8070
          predicates:
            - path=/

        - id : product
          uri: lb://PRODUCT
          predicates:
              - path=/products/**

        - id: client
          uri: lb://CLIENT
          predicates:
              -  path=/clients/**

        - id: order
          uri: lb://ORDER
          predicates:
              - path=/orders/**

        - id: eurekaservicepro
          uri: http://localhost:8761
          predicates:
              - path=/eureka-server/**
