#spring.application.name=GateWay-service

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka

spring:
  application:
    name: GateWay-service

  cloud:
    gateway:
      routes:
        - id : default-root
          uri: http://localhost/:8070
          predicates:
            - path=/
